## 26/11/2025
## Wednesday

# $Pandas$

## Step-1:Import Packages

In [59]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sna

## Step-2 Create a Data Fram using list

In [60]:
names=['Ramesh','Suresh','Mahesh']
pd.DataFrame(names)

        0
0  Ramesh
1  Suresh
2  Mahesh

In [61]:
names=['Ramesh','Suresh','Mahesh']
rows=['A','B','C']
pd.DataFrame(names,rows)

        0
A  Ramesh
B  Suresh
C  Mahesh

In [62]:
names=['Ramesh','Suresh','Mahesh']
rows=['A','B','C']
col=['Names']
pd.DataFrame(names,rows,col)

    Names
A  Ramesh
B  Suresh
C  Mahesh

In [63]:
names=['Ramesh','Suresh','Mahesh']
col=['Names']
pd.DataFrame(names,columns=col)

    Names
0  Ramesh
1  Suresh
2  Mahesh

## Step-3 Multiple Columns

In [64]:
names=['Ramesh','Suresh','Mahesh']
age=[20,22,24]
pd.DataFrame(zip(names,age))

        0   1
0  Ramesh  20
1  Suresh  22
2  Mahesh  24

In [65]:
names=['Ramesh','Suresh','Mahesh']
age=[20,22,24]
pd.DataFrame([names,index:=age])

        0       1       2
0  Ramesh  Suresh  Mahesh
1      20      22      24

In [66]:
names=['Ramesh','Suresh','Mahesh']
age=[20,22,24]
col=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=col)
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Mahesh   24

## Step-7 Add a New Column to already existed data frame work

- In above first we have taken data

- Then created a Data Fram

- Now we want to add new data based on requirements

In [67]:
import pandas as pd
city=['Hyb','Blr','khm']
df['City']=city
df

    Names  Age City
0  Ramesh   20  Hyb
1  Suresh   22  Blr
2  Mahesh   24  khm

In [68]:
marks=[10,25,35]
df['Marks']=marks
df

    Names  Age City  Marks
0  Ramesh   20  Hyb     10
1  Suresh   22  Blr     25
2  Mahesh   24  khm     35

## Step-8 Update the column with new values

In [69]:
df['Marks']=[95,99,99]
df

    Names  Age City  Marks
0  Ramesh   20  Hyb     95
1  Suresh   22  Blr     99
2  Mahesh   24  khm     99

## Step-9 Create Empty Data Frame and add the Columns

In [70]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [71]:
df['Names']=['Ramesh','Suresh','Mahesh','Sathish']
df['Age']=[20,22,24,26]
df['City']=['Hyb','Blr','Khm','pune']
df

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

## Step-10 Create a Data Frame using Dictionary

In [72]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [73]:
d={'Names':['Ramesh','Suresh','Mahesh','Sathish'],'Age':[20,22,24,26],'City':['Hyd','Blr','Khm','pune']}

In [74]:
df=pd.DataFrame(d)
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

In [75]:
d={'Name':'Ramesh','Age':20,'City':'Hyd'}
df=pd.DataFrame(d)
df

ValueError: If using all scalar values, you must pass an index

In [ ]:
d={'Name':'Ramesh','Age':20,'City':'Hyd'}
df=pd.DataFrame(d,[1])
df                         ## IF we provide index it will come

## Step-11 Saving the Data Frame

In [ ]:
##file handling session
# directory//filem=name.ext
# filename.ext
# WE are saving Data Frame
# .csv or xlsv
df.to_csv('First_Data.csv')

In [76]:
df.to_excel('First_Data.xlsx')

## 27/11/2025
## Thursday

## Step-12 Read the Datafram

In [77]:
import pandas as pd
pd.read_csv('First_Data.csv')

   Unnamed: 0    Name  Age City
0           1  Ramesh   20  Hyd

In [78]:
pd.read_excel('First_Data.xlsx')

   Unnamed: 0    Names  Age  City
0           0   Ramesh   20   Hyd
1           1   Suresh   22   Blr
2           2   Mahesh   24   Khm
3           3  Sathish   26  pune

In [79]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [80]:
df['Names']=['Ramesh','Suresh','Mahesh','Sathish']
df['Age']=[20,22,24,26]
df['City']=['Hyb','Blr','Khm','pune']
df

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

## Add one more column marks to df

In [81]:
df['Marks']=[36,99,89,56]
df

     Names  Age  City  Marks
0   Ramesh   20   Hyb     36
1   Suresh   22   Blr     99
2   Mahesh   24   Khm     89
3  Sathish   26  pune     56

## Step-13 Drop the column

- Labels

- Axis

- Index

- Columns

- Inplace

## 
Index

In [82]:
df.drop([0])

     Names  Age  City  Marks
1   Suresh   22   Blr     99
2   Mahesh   24   Khm     89
3  Sathish   26  pune     56

## Axis

In [83]:
df.drop('Marks',axis=1)  ### If axis is 1 then it is remove coulmn only

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

In [84]:
df.drop(1,axis=0) ### If axis is 0 then it takes Row only

     Names  Age  City  Marks
0   Ramesh   20   Hyb     36
2   Mahesh   24   Khm     89
3  Sathish   26  pune     56

In [85]:
df.drop(columns=['Marks'])

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

In [86]:
df.drop(columns=['City','Marks'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2   Mahesh   24
3  Sathish   26

In [87]:
df.drop(index=1)
df.drop(coumns='Marks')
df.drop('Marks') # this is an Label
df.drop(1) # ! becomes label
------------------------------------------
df.drop('Marks')
# By Default label='MArks')
# if axis=1 indicates index
# if axis=1 indicates columns

SyntaxError: invalid syntax (3920155917.py, line 5)

In [88]:
df.drop('Marks',axis=1)

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

In [89]:
df.drop(0,axis=0)

     Names  Age  City  Marks
1   Suresh   22   Blr     99
2   Mahesh   24   Khm     89
3  Sathish   26  pune     56

## Inplace

- When ever we do the operation the result output is not overwrttting 

- Means the Original Data Frame is same as it is.

- Inoreder to do this we use **InPlace**

- By Default **inplace=False**

- Make **Inplace=True** If you want overwrite the result

In [90]:
df.drop('Marks',axis=1,inplace=True)

In [91]:
df

     Names  Age  City
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

## Step 14 Rename the Column

In [92]:
df.rename(columns={'City':'Cites'})  # {'Old':'New'}

     Names  Age Cites
0   Ramesh   20   Hyb
1   Suresh   22   Blr
2   Mahesh   24   Khm
3  Sathish   26  pune

## Mapper

In [93]:
df.rename('Ag)

SyntaxError: unterminated string literal (detected at line 1) (510320935.py, line 1)

## Axis

In [94]:
df.rename('Age',axis=1)

TypeError: Index(...) must be called with a collection of some kind, 'Age' was passed

In [95]:
## Create one more DataFrame 
# x=1 to 10
# y=sqaure x
# z=cube X

In [120]:
df=pd.DataFrame()

In [136]:
df['X']=range(1,10)
df['Y']=np.square(range(1,10))
df['Z']=np.square(range(1,10))*range(1,10)
df

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [98]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x]
df=pd.DataFrame(zip(x,y,z))
df

    0    1     2
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- Len

- Shape

- Size

- Head

- Tail

- Is null

- dtype

- info

In [99]:
len(df)

10

In [103]:
a=df.shape
a

(10, 3)

In [104]:
df.size

30

In [112]:
df.tail()

    0    1     2
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [111]:
df.head()

   0   1    2
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [110]:
df.isnull()

       0      1      2
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [114]:
df.dtypes

0    int64
1    int64
2    int64
dtype: object

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     int64
 1   1       10 non-null     int64
 2   2       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

## Step 15 Select a columns

In [129]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [134]:
df[['X','Y']]

   X   Y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

In [137]:
type(df['X'])      # 1Dimensional Data ,Scalar Data

pandas.core.series.Series

In [138]:
type(df[['X','Y']])       # 2Dimensional Data,Vector Data

pandas.core.frame.DataFrame

In [140]:
df['X'].shape

(9,)

In [141]:
df[['X','Y']].shape

(9, 2)

In [142]:
df # Entire data Frame
df['X'] #Selecting one particular column
df['X'].values # Extracting the Data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
df['Y']

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: Y, dtype: int64

In [144]:
df['Y'].values

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [145]:
df['Z'].values

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [148]:
df[['Y','Z']].values.tolist()

[[1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729]]

In [153]:
df['X'].values.tolist(),df['Y'].values.tolist(),df['Z'].values.tolist()

([1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 4, 9, 16, 25, 36, 49, 64, 81],
 [1, 8, 27, 64, 125, 216, 343, 512, 729])