## 10/12/2025
## Wednesday

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sps

In [2]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

**Feature Engineering**

- So far we have performed feature analysis

  - Data Frame quick checks

  - Categorical column analaysis

  -  Bar Chart, pie Chart

  - Numerical column analysis

  - Histograms, box plot ,outliers

  - Bi verate and Multi Variate analysis

   - correlations etc

- Now we need to learn Feature Engineering

  - We will create a new columns for better ML models

  - We will perform the ** Encoding**, which is convert categorical to Numerical data

  - We will do data **Transformation**

  - We will perform **Scalling: Standardization and Normalization**

  - We will perform **Missing values analysis**

- Simply feature engineering means our data will be modified

## 11/12/2025
## Thursday

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

In [5]:
dtype=visa_df.dtypes
pd.DataFrame(dtype)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [6]:
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [7]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [8]:
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [9]:
visa_df['case_status']=visa_df['case_status'].map(d)

In [10]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [11]:
labels=sorted(visa_df['continent'].unique())
labels

['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

In [62]:
d1={'Africa':0,'Asia':1}
d1

{'Africa': 0, 'Asia': 1}

In [63]:
visa_df['continent']=visa_df['continent'].map(d1)

In [64]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,NaN,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,NaN,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,NaN,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,NaN,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,NaN,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,NaN,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,NaN,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,NaN,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,NaN,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,NaN,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [24]:
for i in labels:
    print(i)

Africa
Asia
Europe
North America
Oceania
South America

In [26]:
labels=sorted(visa_df['continent'].unique())
n=len(labels)
d1={}
for i in labels:
    print(i,i)

Africa Africa
Asia Asia
Europe Europe
North America North America
Oceania Oceania
South America South America

In [41]:
labels=sorted(visa_df['continent'].unique())
d1={}
for i,j in enumerate(labels):
    d1[j]=i

In [42]:
d1

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [68]:
labels=sorted(visa_df['continent'].unique())
d2={j:i for i,j in enumerate(labels)}
visa_df['continent']=visa_df['continent'].map(d2)

In [69]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [95]:
cat=visa_df.select_dtypes(include='object').columns

In [96]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [97]:
for i in cat[1:]:
    labels=sorted(visa_df[i].unique())
    d2={j:i for i,j in enumerate(labels)}
    visa_df[i]=visa_df[i].map(d2)

In [98]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## Label Encoder

- LabelEncoder is a method will convert cat lables to numerical values

- It is under package: **Skilearn (scikit-Learn)**

  - The class Name: **Preprcessing**

      - The method name : **LabelEncoder**

In [ ]:
from <package>.<class>import <method>

In [105]:
from sklearn.preprocessing import LabelEncoder

**Ml**
  
- Step1:import the method

- Step2: save the method

- Step3:apply fit tarnsfer

  - **Fit Transfer**

    - **Fit** means find the logic 

      - in the above example fit means create **mapper** or **dic**
 
   - **Transform** : apply the logic and change the data

    - Apply the **mapperon the Data**

In [106]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [110]:
# Import the method
from sklearn.preprocessing import LabelEncoder
# Savve the method
le=LabelEncoder()
# Apply fit tansform
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0])

In [111]:
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [112]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [113]:
# Import the method
from sklearn.preprocessing import LabelEncoder
# Savve the method
le1=LabelEncoder()
# Apply fit tansform
le1.fit_transform(visa_df['continent'])

array([1, 1, 1, ..., 1, 1, 1])

In [114]:
visa_df['continent']=le1.fit_transform(visa_df['continent'])

In [115]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [121]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [122]:
from sklearn.preprocessing import LabelEncoder
# Savve the method
le1=LabelEncoder()
# Apply fit tansform
for i in cat[1:]:
    le1.fit_transform(visa_df[i])
    visa_df[i]=le1.fit_transform(visa_df[i])

In [123]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

## OneHotEncoder

- Frist hoe many labels are their in columns

- that many new columns are created extra

- for example case status has two labels

  - Ceritfied

  - Denied

- So it will create Two new extra columns

  - Case_status_Certified

  - Case_status_Denied

- At at time one columns values become 1 other coumn values become 0

- This means A **One Hot Encoder**

|Case_Status_Certified||case_status_Denied|

|case_stauts||Case_Status_Certified||case_status_Denied|
|---||-||-|
|Certified||1|0|
|Denied||0|1|

## Pd.get_dummies

In [124]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [128]:
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [127]:
pd.get_dummies(visa_df['continent'],dtype=int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

## 12/12/2025
## Friday

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
file_path=r'C:\Users\DELL\Documents\Naresh IT( Data Science and Genrative AI )\Data Files\Visadataset.csv'
visa_df=pd.read_csv(file_path)

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns